export const commonFoodAllergens = [
  "Mleko krowie",
  "Jaja kurze",
  "Ryby",
  "Skorupiaki (np. krewetki, kraby, homary, raki)",
  "Orzeszki ziemne (arachidowe)",
  "Orzechy drzewa (migdały, orzechy laskowe, włoskie, nerkowce, pekan, brazylijskie, pistacje, makadamia)",
  "Soja",
  "Pszenica (gluten)",
  "Seler",
  "Gorczyca",
  "Nasiona sezamu",
  "Dwutlenek siarki i siarczyny",
  "Łubin",
  "Mięczaki (małże, kalmary, ślimaki, ostrygi, ośmiornice)",
  // Dodatkowe często uczulające pokarmy
  "Pomidor",
  "Marchew",
  "Jabłko",
  "Cytrusy (np. pomarańcze, cytryny)",
  "Truskawki",
  "Banany",
  "Czekolada",
];
